#!/bin/bash

forever="$(which forever 2>/dev/null)";
if [ $? -gt 0 ];
    then
        echo "系统需要Forever,尝试运行安装脚本sudo npm install forever -g"
        exit 1;
fi

case "$1" in
    start)
        echo "正在启动 Eagle 系统";
        FOREVER_ROOT=$(pwd) forever start -o logs/output.log -e logs/error.log -l logs/forever.log app.js
        ;;

    stop)
        FOREVER_ROOT=$(pwd) forever stop app.js 
        ;;

    restart)
        FOREVER_ROOT=$(pwd) forever restart app.js
        ;;

    log)
        if [ -e logs/forever.log ];
            then
                clear;
                tail -f logs/forever.log;
            else
                echo "没有日志文件";
                exit 1
        fi
        ;;

    *)
        echo "用法 $0 {start|stop|restart|log}";
        exit 1;
        ;;
esac
